
name: ros2-images-CI

on:
  push:
    branches: 
    - 'feature/**' 
    - main
    - devel
  pull_request:
    branches: 
    - main
    # - devel 

  workflow_dispatch:

jobs:
  build_and_push_galactic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      # Build ros2 images and push to docker hub
      - name: Run docker build and push galactic
        env:
          COMPUTE: cpu
          ROS_DISTRO: galactic
        run: |
          make clean
          make
          make push
      
      # unittest
      - name: run structure tests
        uses: plexsystems/container-structure-test-action@v0.1.0
        with:
          image: ameyawagh/ros2-images:galactic-full
          config: tests.yaml
  
  build_and_push_foxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}        
      - name: Run docker build and push foxy
        env:
          ROS_DISTRO: foxy
        run: |
          make clean
          make
          make push
  
  build_and_push_eloquent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}        
      - name: Run docker build and push eloquent
        env:
          ROS_DISTRO: eloquent
        run: |
          make clean
          make
          make push
  
  build_and_push_dashing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run docker build and push dashing
        env:
          ROS_DISTRO: dashing
        run: |
          make clean
          make
          make push
